#!/usr/bin/env python3
# Copyright 2010-2012 Lee Harr
#
# This file is part of pynguin.
# http://pynguin.googlecode.com/
#
# Pynguin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pynguin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pynguin.  If not, see <http://www.gnu.org/licenses/>.


import sys
import os


def setup_devel():
    # Change current dir to where this file lives
    filepath = os.path.realpath(__file__)
    filedir, _ = os.path.split(filepath)
    os.chdir(filedir)

    # Use the pynguin lib here in the lib folder.
    # For development, or running from the source
    #   folder instead of a proper install.
    sys.path.insert(0, 'lib')

def make_deb():
    import shutil
    import glob
    from pynguin import conf

    if os.path.exists('deb_dist'):
        shutil.rmtree('deb_dist')

    backuppattern = 'backup~%s.pyn'
    logfile = 'logfile.log'

    backups = glob.glob(backuppattern % '*')
    for b in backups:
        os.remove(b)
    if os.path.exists(logfile):
        os.remove(logfile)

    os.system('python setup.py bdist_deb')
    os.chdir('deb_dist/%s/' % conf.version)
    f = open('debian/rules', 'a')
    f.write('override_dh_compress:\n')
    f.write('\tdh_compress -X.pyn\n')
    f.close()
    os.system('dpkg-buildpackage -rfakeroot -uc -us')

if '-d' in sys.argv:
    setup_devel()

    if 'MAKEDEB' in sys.argv:
        make_deb()
        sys.exit(0)


try:
    from pynguin import main
except ImportError:
    # No install found. Try to locate pynguin lib locally
    if '-d' not in sys.argv:
        sys.argv.append('-d')

    setup_devel()

    try:
        from pynguin import main
    except ImportError:
        print('Unable to locate the pynguin libraries.')
        print('Check your installation.')
        main = False


if main:
    if '-D' in sys.argv:
        main.setup_logging()

    from pynguin import util
    if not util.check_data_doc_dir():
        print('Unable to locate pynguin data.')
        print('Check your installation.')
        main = False

    if util.__file__.startswith('/usr/local') and sys.prefix == '/usr':
        print()
        print('If this is a Debian or Ubuntu system,')
        print('You may have forgotten to pass')
        print('--install-layout=deb')
        print('when installing.')


def help():
    from pynguin import conf
    print(conf.version)
    print()
    print('options:')
    print('  -h : this help text')
    print('  -d : development mode. Run from local directory')
    print('  -D : debug mode. Write debug info to log file')
    print(' DUMP <filename> :')
    print('       dump contents of pynguin file to standard output')
    print('  -d MAKEDEB : create debian package')

if '-h' in sys.argv:
    help()
elif main and 'DUMP' in sys.argv:
    main.dumpfile()
elif main:
    main.run()
else:
    input()
