#!/usr/bin/env python
# Copyright 2010 Lee Harr
#
# This file is part of pynguin.
# http://pynguin.googlecode.com/
#
# Pynguin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pynguin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pynguin.  If not, see <http://www.gnu.org/licenses/>.


import sys

if '-d' in sys.argv:
    # Use the pynguin lib here in the lib folder.
    # For development, or running from the source
    #   folder instead of a proper install.
    sys.path.insert(0, 'lib')

try:
    from pynguin import main
except ImportError:
    # No install found. Try to locate pynguin lib locally
    if '-d' not in sys.argv:
        sys.argv.append('-d')

    sys.path.insert(0, 'lib')
    try:
        from pynguin import main
    except ImportError:
        print 'Unable to locate the pynguin libraries.'
        print 'Check your installation.'
        main = False


if main:
    from pynguin import util
    if not util.check_data_doc_dir():
        print 'Unable to locate pynguin data.'
        print 'Check your installation.'
        main = False

if main:
    main.run()
else:
    raw_input()
